services:
  panel:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env.production
    expose:
      - "3000"
    networks:
      backend:
        aliases:
          - salgados-encomendas-panel

networks:
  backend:
    external: true
    name: salgados_backend_net
